[nodes]
con0:_ radius=1 angle=1
agg0:_ radius=2 angle=2
agg1:_ radius=3 angle=3
pro0:_ radius=4 angle=4
pro1:_ radius=5 angle=5
pro2:_ radius=6 angle=6
pro3:_ radius=7 angle=7

[links]
con0:agg0 bw=30 delay=2ms max_queue_size=1000 loss=0
con0:agg1 bw=30 delay=2ms max_queue_size=1000 loss=0
agg0:pro0 bw=30 delay=2ms max_queue_size=1000 loss=0
agg0:pro1 bw=30 delay=2ms max_queue_size=1000 loss=0
agg1:pro2 bw=30 delay=2ms max_queue_size=1000 loss=0
agg1:pro3 bw=30 delay=2ms max_queue_size=1000 loss=0
